# Copyright (c) 2026 Pointmatic, (https://www.pointmatic.com)
# SPDX-License-Identifier: Apache-2.0
# shellcheck shell=bash
#============================================================
# lib/envrc_composer.sh — composed `.envrc` builder (Story N.ae)
#
# Stands up the central composer that gathers every active plugin's
# activation snippet into one `.envrc` body with sentinel-marked plugin
# sections (the PC-2 composition layer from the Phase N plan).
#
# Two halves, two stories:
#   - N.ae.3 (here): `_compose_envrc_body` — pure assembly + PC-1
#     validation. Enumerates active plugins, dispatches each plugin's
#     `pyve_plugin_activate` (snippet emitter, per N.ae.2 / N.y),
#     concatenates the sentinel-wrapped sections, validates the plugin
#     sections through `validate_envrc_snippet`, and wraps everything in
#     the managed envelope with composer-owned infrastructure appended
#     AFTER validation. Emits the managed body to stdout — no file write.
#   - N.ae.4: `compose_envrc <path>` — the atomic writer (`.tmp` → `.prev`
#     → `mv`) with user-content preservation below the end marker.
#
# Contract reference: docs/specs/spike-n-ae-envrc-composer-contract.md.
#============================================================

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    printf "Error: %s is a library and cannot be executed directly.\n" "${BASH_SOURCE[0]}" >&2
    exit 1
fi

# Managed-section sentinels. User-authored content lives below the end
# marker (preserved verbatim by compose_envrc in N.ae.4).
ENVRC_MANAGED_START="# >>> pyve:managed:start >>>"
ENVRC_MANAGED_END="# <<< pyve:managed:end <<<"

# Assemble the managed `.envrc` body and emit it to stdout.
#
# Steps:
#   1. Enumerate active plugins (plugin_list_active, N.k).
#   2. For each, dispatch `pyve_plugin_activate "<manifest path>"`; the
#      hook emits a sentinel-wrapped section to stdout (N.ae.2 / N.y).
#      A failing hook (e.g. PC-1 caught smuggling inside the plugin)
#      halts the whole compose.
#   3. Validate the concatenated plugin sections via PC-1
#      (validate_envrc_snippet). Defense in depth — each plugin already
#      validates its own snippet — and the composer's contract gate.
#   4. Wrap in the managed envelope. Composer-owned infrastructure (the
#      dotenv block + the asdf reshim guard when `is_asdf_active`) is
#      appended AFTER validation: it is static pyve text that cannot pass
#      the strict PC-1 allow-list (multi-line `if`; unquoted export).
#
# Returns non-zero (emitting nothing usable) when any plugin hook fails
# or the composed plugin sections fail PC-1.
_compose_envrc_body() {
    local name path section
    local plugin_body=""

    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        path="$(manifest_get_plugin_path "$name" 2>/dev/null || true)"
        if ! section="$(plugin_dispatch "$name" activate "$path")"; then
            log_error "envrc_composer: plugin '$name' activate hook failed — no .envrc composed"
            return 1
        fi
        plugin_body+="${section}"$'\n'
    done < <(plugin_list_active)

    if ! validate_envrc_snippet "$plugin_body"; then
        log_error "envrc_composer: composed plugin sections failed PC-1 validation"
        return 1
    fi

    # ── Emit the managed section ────────────────────────────────────
    printf '# pyve-managed direnv configuration\n'
    printf '# Generated by pyve. Do not edit between the managed markers below;\n'
    printf '# add your own direnv configuration beneath the end marker.\n'
    printf '%s\n' "$ENVRC_MANAGED_START"
    printf '%s' "$plugin_body"

    # ── Composer-owned infrastructure (appended after PC-1) ─────────
    printf '\nif [[ -f ".env" ]]; then\n    dotenv\nfi\n'
    if is_asdf_active; then
        printf '\n# Prevent asdf Python plugin from reshimming venv-installed CLIs.\n'
        printf '# Override with PYVE_NO_ASDF_COMPAT=1 to restore default asdf reshim behavior.\n'
        printf 'export ASDF_PYTHON_PLUGIN_DISABLE_RESHIM=1\n'
    fi

    printf '%s\n' "$ENVRC_MANAGED_END"
}
